<div class="container">

	<h2 class="mb-3">Registrazione utente</h2>
	<p class="lead">Registrati al sito web per poter prenotare direttamente online le varie prestazioni offerte dalla struttura sanitaria.</p>

	<form>
		<div class="form-group">
			<label for="InputEmail">Email</label>
			<input type="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" placeholder="Inserisci la tua mail">
			<small id="emailHelp" class="form-text text-muted">La mail deve essere valida, in quanto i promemoria delle prenotazioni saranno inviati a questo indirizzo.</small>
		</div>
		<div class="form-group">
			<label for="InputUsername">Username</label>
			<input type="text" class="form-control" id="InputUsername" placeholder="Inserisci un'username">
			<small id="emailHelp" class="form-text text-muted">Crea un username utilizzando lettere maiuscole e minuscole, i numeri e i caratteri "_", "-".</small>
		</div>
		<div class="form-group">
			<label for="InputPassword">Password</label>
			<input type="password" class="form-control" id="InputPassword" placeholder="Inserisci la password">
			<small id="emailHelp" class="form-text text-muted">Utilizza una password sicura che contenga numeri, lettere e che sia almeno di 8 caratteri.</small>
		</div>
		<div class="form-group">
			<label for="InputName">Nome</label>
			<input type="text" class="form-control" id="InputName" placeholder="Inserisci il tuo nome">
			<small id="emailHelp" class="form-text text-muted">Inserire il proprio nome in questo form.</small>
		</div>
		<div class="form-group">
			<label for="InputSurname">Cognome</label>
			<input type="text" class="form-control" id="InputSurname" placeholder="Inserisci il tuo nome">
			<small id="emailHelp" class="form-text text-muted">Inserire il proprio cognome in questo form.</small>
		</div>
		<div class="form-group">
			<label for="InputCode">Codice Fiscale</label>
			<input type="text" class="form-control" id="InputCode" placeholder="Inserisci il codice fiscale">
			<small id="emailHelp" class="form-text text-muted">Inserire il proprio codice fiscale.</small>
		</div>

		<button type="submit" class="btn btn-primary">Registrati</button>
	</form>
</div>