<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>Health Facility | Gianluca Bonifazi - Progetto Tecnologie Web</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>

    <header>
        <section>
            <h1>Health Facility</h1>
            <img src="img/heartbeats.png">
            <h2><u>Sito web in costruzione!</u></h2>
        </section>
    </header>

    <footer>
        <u>Progetto Tecnologie Web</u> <br> <strong>Gianluca Bonifazi ~ 1082209</strong>
    </footer>

</body>
</html>