<div class="container">

	<div class="jumbotron">
		<p class="text-center"><img src="img/heartbeats.png" style="max-width: 256px"></p>
		<h1 class="display-4">Health Facility</h1>
		<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		<hr class="my-4">
		<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	</div>

	<p class="text-danger">
	- Mission della struttura<br>
	- Organizzazione interna dei servizi<br>
	- Informazioni generali
	</p>
</div>
