<div class="container">
	<h2 class="mb-3">Chat</h2>
	<p class="lead pb-3">Utilizza questa chat per parlare con l'utente.</p>
	<div class="messaging">
		<div class="inbox_msg">
			<div class="mesgs">
				<div class="msg_history">
					<?php
						$exData = null;
						foreach ($this->messages as $value) {
							$timestamp = strtotime($value['time']);
							$day = date('M d', $timestamp);
							$time = date('H:i:s', $timestamp);
							if ($exData != $day) {
								echo '<hr class="hr-text" data-content="'.$day.'">';
							}
							if ($value['user'] != $this->userId) {
								echo '<div class="outgoing_msg">';
								echo '<div class="sent_msg">';
								echo '<p>'.$value['message'].'</p>';
								echo '<span class="time_date"><strong>'.$value['name'].' '.$value['surname'].'</strong> - '.$time.'</span></div>';
								echo '</div>';
							} else {
								echo '<div class="incoming_msg">';
								echo '<div class="incoming_msg_img"> <img src="'.APP_URL.'/img/chat_user.png" alt="doctor"> </div>';
								echo '<div class="received_msg">';
								echo '<div class="received_withd_msg">';
								echo '<p>'.$value['message'].'</p>';
								echo '<span class="time_date"><strong>'.$value['name'].' '.$value['surname'].'</strong> - '.$time.'</span></div>';
								echo '</div>';
								echo '</div>';
							}
							$exData = $day;
						}
					?>
				</div>
				<div class="type_msg mt-3">
					<div class="input_msg_write">
						<input type="text" class="write_msg" placeholder="Scrivi un messaggio..." />
						<button class="msg_send_btn" type="button"><i class="fas fa-paper-plane"></i></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	<?php
		$dateTime = new DateTime();
		$dateTime->setTimezone(new DateTimeZone('Europe/Rome'));
		$dateNow = $dateTime->format('Y-m-d H:i:s');
	?>
	var chatPage = true;
	var urlAjaxSend = '<?= $this->url(array('controller' => 'staff', 'action' => 'send')); ?>';
	var urlAjaxGet = '<?= $this->url(array('controller' => 'staff', 'action' => 'get')); ?>';
	var user_id = <?= Zend_Auth::getInstance()->getIdentity()->user_id; ?>;
	var lastRefresh = '<?= $dateNow; ?>';
	var timeRefresh = 1500;
	var imgUrl = '<?=APP_URL?>';
	var userChatId = <?= $this->userId; ?>;
</script>