<div class="container">
	<h2 class="mb-3">Chat - Lista Utenti</h2>
	<p class="lead pb-3">Scegli un utente dalla lista per avviare la chat.</p>
	<ul class="list-group list-group-flush">
		<?php
			foreach ($this->userList as $value) {
				echo '<li class="list-group-item">';
				echo '<i class="far fa-comments"></i> <a href="'.$this->url(array('controller' => 'staff', 'action' => 'chat', 'id' => $value['user_id'])).'">'.$value['name'].' '.$value['surname'].'</a>';
				echo '</li>';
			}
		?>
	</ul>
</div>