<div class="container">

	<h2 class="mb-3">Login utente</h2>
	<p class="lead">Effettua il login in questa pagina per poter accedere all'area riservata dell'utente e per poter prenotare i vari servizi.</p>

	<form>
		<div class="form-group">
			<label for="InputUsername">Username</label>
			<input type="email" class="form-control" id="InputUsername" placeholder="Inserisci l'username">
		</div>
		<div class="form-group">
			<label for="InputPassword">Password</label>
			<input type="password" class="form-control" id="InputPassword" placeholder="Inserisci la password">
		</div>

		<button type="submit" class="btn btn-primary">Login</button>
	</form>
</div>