<div class="container">

	<h2 class="mb-3">Login utente</h2>
	<p class="lead">Effettua il login in questa pagina per poter accedere alla tua area riservata.</p>

	<?php 
		$error = isset($_GET['err']) ? $_GET['err'] : '';
		if ($error == 1) {
	?>
		<div class="alert alert-danger" role="alert">
			<strong>ATTENZIONE!</strong> Il nome utente o la password che hai inserito <u>non sono corretti</u>!
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<?php
		}
	?>

	<?php 
		$registration = isset($_GET['reg']) ? $_GET['reg'] : '';
		if ($registration == 1) {
	?>
		<div class="alert alert-success" role="alert">
			<strong>Registrazione andata a buon fine!</strong> Effettua il login con le tue credenziali.
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<?php
		}
	?>

	<form action="<?php echo $this->url(array('controller' => 'login', 'action' => 'enter')); ?>" method="POST">
		<div class="form-group">
			<label for="InputUsername">Username</label>
			<input type="text" class="form-control" id="InputUsername" name="username" placeholder="Inserisci l'username">
		</div>
		<div class="form-group">
			<label for="InputPassword">Password</label>
			<input type="password" class="form-control" id="InputPassword" name="password" placeholder="Inserisci la password">
		</div>

		<button type="submit" class="btn btn-primary">Login</button>
	</form>

</div>