<?= $this->doctype(); ?>
<html lang="it-IT">
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink(); ?>
</head>
<body>
	<header class="mb-4">
		<nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="<?= $this->url(array('controller' => 'admin', 'action' => 'index')); ?>"><img src="<?=APP_URL?>/img/admindashboard.png"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'index')); ?>">Dashboard</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'users')); ?>">Utenti</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'staff')); ?>">Staff</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'department')); ?>">Dipartimenti</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'booking')); ?>">Prenotazioni</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="<?= $this->url(array('controller' => 'admin', 'action' => 'logout')); ?>">Logout</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<?= $this->layout()->content; ?>

	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				&copy; <em>Gianluca Bonifazi</em> ~ <small>1082209</small>
				<a href="" class="float-right">Documentazione</a>
			</span>
		</div>
	</footer>

    <?= $this->InlineScript(); ?>
</body>
</html>