<?= $this->doctype(); ?>
<html lang="it-IT">
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink(); ?>
</head>
<body>
	<ul class="list-inline container my-4">
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin">Home</a>&nbsp;&nbsp;-</li>
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin/users">Uenti</a>&nbsp;&nbsp;-</li>
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin/staff">Staff</a>&nbsp;&nbsp;-</li>
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin/department">Dipartimenti</a>&nbsp;&nbsp;-</li>
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin/booking">Prenotazioni</a>&nbsp;&nbsp;-</li>
		<li class="list-inline-item"><a href="<?=APP_URL?>/admin/logout">Logout</a></li>
	</ul>

	<?= $this->layout()->content; ?>

    <?= $this->InlineScript(); ?>
</body>
</html>