<div class="container">
  <div class="alert alert-danger mt-5" role="alert">
    <h5 class="alert-heading">ATTENZIONE! L'applicazione ha riscontrato il seguente errore:</h5>
    <p class="mb-0"><u><?= $this->message; ?></u>!</p>
  </div>

<?php if (isset($this->exception)): ?>
<hr>

<h5>Exception information:</h5>
<p>
<b>Message:</b> <?= $this->exception->getMessage(); ?>
</p>

<h5>Stack trace:</h5>
<pre>
<?= $this->exception->getTraceAsString(); ?>
</pre>

<h5>Request Parameters:</h5>
<pre>
<?= $this->escape(var_export($this->request->getParams(), true)); ?>
</pre>

<?php endif ?>

  </div>