<div class="container">

	<h2 class="mb-3">Cerca prestazione</h2>
	<p class="lead">Usa il form di ricerca sottostante per trovare una prestazione offerta dalla struttura ospedaliera.</p>

	<form>
		<div class="form-row align-items-center mb-4">
			<div class="col-sm-4 my-1">
				<label class="mr-sm-2" for="departmentSelect">Scegli il dipartimento:</label>
				<select class="custom-select mr-sm-2" id="departmentSelect">
					<option selected>Scegli...</option>
				</select>
			</div>
			<div class="col-sm-4 my-1" id="chooseService">
				<label class="mr-sm-2" for="serviceSelect">Scegli la prestazione:</label>
				<select class="custom-select mr-sm-2" id="serviceSelect">
					<option selected>Scegli...</option>
				</select>
			</div>
			<div class="col-sm-4 my-1" id="viewService">
				<a href="#" class="btn btn-info btn-block">Vedi dettagli</a>
			</div>
		</div>
	</form>
	
	<hr>

	<form class="pb-3">
		<label class="mr-sm-2" for="searchByName">Oppure scrivi quello che stai cercando:</label>
		<div class="input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"><i class="fas fa-search"></i></span>
			</div>
			<input type="text" class="form-control" name="searchByName" id="searchByName">
		</div>
	</form>
	<section id="searchResult" class="pb-3"></section>

</div>

<script>
	var search = <?= $this->search ?> 
</script>