<div class="container">
	<ul class="list-inline text-right userMenu">
		<li class="list-inline-item">
			<i class="far fa-calendar-alt"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'index')); ?>">Prenotazioni</a>
		</li>
		<li class="list-inline-item"> - </li>
		<li class="list-inline-item">
			<i class="fas fa-user-edit"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'profile')); ?>">Modifica Profilo</a>
		</li>
		<li class="list-inline-item"> - </li>
		<li class="list-inline-item">
			<i class="fas fa-comments"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'chat')); ?>"><u>Assistenza</u></a>
		</li>
	</ul>
</div>

<section class="container">
	<h2 class="mb-3">Chat</h2>
	<p class="lead pb-3">Hai bisogno di aiuto? Usa questa chat per parlare con l'assistenza.</p>

	<div class="messaging">
		<div class="inbox_msg">
			<div class="mesgs">
				<div class="msg_history">
					<?php
						$exData = null;
						foreach ($this->messages as $value) {
							$timestamp = strtotime($value['time']);
							$day = date('M d', $timestamp);
							$time = date('H:i:s', $timestamp);
							if ($exData != $day) {
								echo '<hr class="hr-text" data-content="'.$day.'">';
							}
							if ($value['user'] == $this->userId) {
								echo '<div class="outgoing_msg">';
								echo '<div class="sent_msg">';
								echo '<p>'.$value['message'].'</p>';
								echo '<span class="time_date"><strong>'.$value['name'].' '.$value['surname'].'</strong> - '.$time.'</span></div>';
								echo '</div>';
							} else {
								echo '<div class="incoming_msg">';
								echo '<div class="incoming_msg_img"> <img src="'.APP_URL.'/img/chat_doctor.png" alt="doctor"> </div>';
								echo '<div class="received_msg">';
								echo '<div class="received_withd_msg">';
								echo '<p>'.$value['message'].'</p>';
								echo '<span class="time_date"><strong>'.$value['name'].' '.$value['surname'].'</strong> - '.$time.'</span></div>';
								echo '</div>';
								echo '</div>';
							}
							$exData = $day;
						}
					?>
				</div>
				<div class="type_msg mt-3">
					<div class="input_msg_write">
						<input type="text" class="write_msg" placeholder="Scrivi un messaggio..." />
						<button class="msg_send_btn" type="button"><i class="fas fa-paper-plane"></i></button>
					</div>
				</div>
			</div>
		</div>
		<p class="pt-2 text-center"><small class="text-secondary">INFO: se il messaggio inviato non viene visualizzato nella chat fare il refresh della pagina.</small></p>
	</div>
</section>

<script>
	<?php
		$dateTime = new DateTime();
		$dateTime->setTimezone(new DateTimeZone('Europe/Rome'));
		$dateNow = $dateTime->format('Y-m-d H:i:s');
	?>
	var chatPage = true;
	var urlAjaxSend = '<?= $this->url(array('controller' => 'user', 'action' => 'send')); ?>';
	var urlAjaxGet = '<?= $this->url(array('controller' => 'user', 'action' => 'get')); ?>';
	var user_id = <?= Zend_Auth::getInstance()->getIdentity()->user_id; ?>;
	var lastRefresh = '<?= $dateNow; ?>';
	var timeRefresh = 5000;
	var imgUrl = '<?=APP_URL?>';
</script>