<div class="container">
	<ul class="list-inline text-right">
		<li class="list-inline-item">
			<i class="far fa-calendar-alt"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'index')); ?>">Prenotazioni</a>
		</li>
		<li class="list-inline-item"> - </li>
		<li class="list-inline-item">
			<i class="fas fa-user-edit"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'profile')); ?>"><u>Modifica Profilo</u></a>
		</li>
		<li class="list-inline-item"> - </li>
		<li class="list-inline-item">
			<i class="fas fa-comments"></i> 
			<a class="text-info font-weight-light" href="<?= $this->url(array('controller' => 'user', 'action' => 'chat')); ?>">Assistenza</a>
		</li>
	</ul>
</div>

<section class="container">
	Modifica Profilo
</section>