<div class="container">

	<h2 class="mb-3">Contatti</h2>

	<div class="row">
		<div class="col-md-6">
			In questa pagina sono presenti tutte le informazioni utili per mettersi in contatto con la nostra struttura. &Egrave; inoltre disponibile una mappa interattiva per ricevere indicazioni stradali.
			<ul class="mt-2">
				<li>
					<strong>Email:</strong> <a href="mailto:info@healthfacility.com">info@healthfacility.com</a>
				</li>
				<li>
					<strong>Tel:</strong> 071 7834567
				</li>
				<li>
					<strong>Fax:</strong> 071 7834568
				</li>
				<hr>
				<li><u>Primari</u></li>
				<ul>
					<li><em>Giuseppe Verdi</em></li>
					<ul>
						<li><a href="mailto:g_verdi@healthfacility.com">g_verdi@healthfacility.com</a></li>
						<li>071 7834569</li>
					</ul>
					<li><em>Mario Bianchi</em></li>
					<ul>
						<li><a href="mailto:m_bianchi@healthfacility.com">m_bianchi@healthfacility.com</a></li>
						<li>071 7834570</li>
					</ul>
				</ul>

				<li><u>Assistenza</u></li>
				<ul>
					<li><em>Centralino 24h</em></li>
					<ul>
						<li><a href="mailto:help@healthfacility.com">help@healthfacility.com</a></li>
						<li>071 7834571</li>
					</ul>
					<li><em>Amministrazione</em></li>
					<ul>
						<li><a href="mailto:amministrazione@healthfacility.com">amministrazione@healthfacility.com</a></li>
						<li>071 7834572</li>
					</ul>
			</ul>
		</div>
		<div class="col-md-6">
			<div class="map-responsive">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1768.2264453729958!2d13.454506238468676!3d43.6037844980304!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdd8ec34d6e7d2d85!2sOspedali+Riuniti+Torrette+Di+Ancona!5e0!3m2!1sit!2sit!4v1535981658046" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
			<small class="d-block text-right mt-3">Via Conca, 71, 60030 Torrette, Ancona AN</small>
		</div>
	</div>
</div>