<div class="container pb-4">
	<h2 class="mb-3">Gestione Prenotazioni</h2>
	<p class="lead pb-3">In questa pagina è possibile vedere tutte le prenotazioni con la possibilitò di modificarle, inserirne nuove e/o cancellarle.</p>

	<div class="text-center">
		<a href="<?= $this->url(array('controller' => 'admin', 'action' => 'insertbooking')); ?>" class="btn btn-outline-success"><i class="fas fa-plus-circle"></i> Inserisci nuovo</a>
	</div>
	
	<div class="table-responsive mt-2">
		<table id="dataTable" class="table table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>Servizio</th>
	                <th>Paziente</th>
	                <th>Data</th>
	                <th>Ora</th>
	                <th>Azioni</th>
	            </tr>
	        </thead>
	        <tbody>
	        	<?php
	        		foreach ($this->allReservations as $value) {
	        			echo '<tr id="row'.$value['booking_id'].'">';
	        			echo '<td>'.$value['service'].'</td>';
	        			echo '<td>'.$value['name'].' '.$value['surname'].'</td>';
	        			echo '<td>'.date('d/m/Y', strtotime($value['date'])).'</td>';
	        			echo '<td>'.date('H:i', strtotime($value['date'])).'</td>';
						echo '<td class="text-center">';
							echo '<a class="text-dark deleteAction" data-toggle="tooltip" data-placement="top" title="Cancella" data-primary="'.$value['booking_id'].'"><i class="fas fa-trash-alt"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark updateAction" data-toggle="tooltip" data-placement="top" title="Modifica" data-primary="'.$value['booking_id'].'" data-toggle="modal" data-target="#updateModal"><i class="fas fa-edit"></i></a>';
						echo '</td>';
	        			echo '</tr>';
	        		}
	        	?>
	        </tbody>
	    </table>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modifica Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
		<form>
			<div class="form-group">
				<label>Data</label>
				<div class="row">
				<?php 
					$timestamp = time();

					$selected_month = date('n', $timestamp);
					$selected_day = date('j', $timestamp);
					$selected_year = date('Y', $timestamp);

					$month_html = '<select name="date_mo" class="form-control">';
					for ($x = 1; $x < 13; $x++) {
					    $month_html .= '<option value='.$x.($selected_month == $x ? ' selected=true' : '' ).'>'.date("F", mktime(0, 0, 0, $x, 1, $selected_year)).'</option>';
					}
					$month_html .= '</select>';
					echo '<div class="col">'.$month_html.'</div>';

					$day_html = '<select name="date_day" class="form-control">';
					for ($x = 1; $x < 32; $x++) {
					    $day_html .= '<option value='.$x.($selected_day == $x ? ' selected=true' : '' ).'>'.$x.'</option>';
					}   
					$day_html .= '</select>';
					echo '<div class="col">'.$day_html.'</div>';

					$year_html = '<select name="date_year" class="form-control">';
					$start_year = date('Y', time());
					$max_year = $start_year + 51;
					for ($x = $start_year; $x < $max_year; $x++) {
					    $year_html .= '<option value='.$x.($selected_year == $x ? ' selected=true' : '' ).'>'.$x.'</option>';
					}   
					$year_html .= '</select>';
					echo '<div class="col">'.$year_html.'</div>';
				?>
				</div>
			</div>
			<div class="form-group">
				<label>Ora</label>
				<select class="form-control modalInput-hour" name="hour">
					<option value="">Scegli un'ora...</option>
					<?php
						$start = '00:00';
						$end = '23:00';

						$tStart = strtotime($start);
						$tEnd = strtotime($end);
						$tNow = $tStart;

						while($tNow <= $tEnd){
						  echo '<option value="'.date("H:i",$tNow).'">'.date("H:i",$tNow).'</option>';
						  $tNow = strtotime('+1 hour',$tNow);
						}
					?>
				</select>
			</div>
      		<input type="hidden" name="user" class="modalInput-user">
      		<input type="hidden" name="service" class="modalInput-service">
      		<input type="hidden" name="typeOfRecord" value="booking">
      		<input type="hidden" name="primariKey" class="modalInput-key">
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <button type="button" class="btn btn-primary" id="sendUpdateBook">Modifica</button>
      </div>
    </div>
  </div>
</div>

<script>
	var dataTableInit = true;

	var typeOfRecord = 'booking';
	var ajaxUrlDel   = '<?= $this->url(array('controller' => 'admin', 'action' => 'deleterecord')); ?>';
	var ajaxUrlGet 	 = '<?= $this->url(array('controller' => 'admin', 'action' => 'getrecord')); ?>';
	var ajaxUrlUpd 	 = '<?= $this->url(array('controller' => 'admin', 'action' => 'updaterecord')); ?>';
</script>