<div class="container pb-4">
	<h2 class="mb-3">Gestione FAQs</h2>
	<p class="lead pb-3">In questa pagina è possibile vedere tutte le FAQ con la possibilitò di modificarle, inserirne nuove e/o cancellarle.</p>

	<div class="text-center">
		<a href="<?= $this->url(array('controller' => 'admin', 'action' => 'insertfaq')); ?>" class="btn btn-outline-success"><i class="fas fa-plus-circle"></i> Inserisci nuovo</a>
	</div>
	
	<div class="table-responsive mt-2">
		<table id="dataTable" class="table table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>Domanda</th>
	                <th>Risposta</th>
	                <th>Azioni</th>
	            </tr>
	        </thead>
	        <tbody>
	        	<?php
	        		foreach ($this->allFaq as $value) {
	        			echo '<tr id="row'.$value['faq_id'].'">';
	        			echo '<td>'.$value['question'].'</td>';
	        			echo '<td>'.$value['answer'].'</td>';
						echo '<td class="text-center">';
							echo '<a class="text-dark deleteAction" data-toggle="tooltip" data-placement="top" title="Cancella" data-primary="'.$value['faq_id'].'"><i class="fas fa-trash-alt"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark updateAction" data-toggle="tooltip" data-placement="top" title="Modifica" data-primary="'.$value['faq_id'].'" data-toggle="modal" data-target="#updateModal"><i class="fas fa-edit"></i></a>';
						echo '</td>';
	        			echo '</tr>';
	        		}
	        	?>
	        </tbody>
	    </table>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modifica Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
		<form>
			<div class="form-group">
				<label>Domanda</label>
      			<input type="text" name="question" class="form-control modalInput-question">
			</div>
			<div class="form-group">
				<label>Risposta</label>
				<textarea class="form-control modalInput-answer" name="answer" rows="4"></textarea>
			</div>
      		<input type="hidden" name="typeOfRecord" value="faq">
      		<input type="hidden" name="primariKey" class="modalInput-key">
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <button type="button" class="btn btn-primary" id="sendUpdateBook">Modifica</button>
      </div>
    </div>
  </div>
</div>

<script>
	var dataTableInit = true;

	var typeOfRecord = 'faq';
	var ajaxUrlDel   = '<?= $this->url(array('controller' => 'admin', 'action' => 'deleterecord')); ?>';
	var ajaxUrlGet   = '<?= $this->url(array('controller' => 'admin', 'action' => 'getrecord')); ?>';
	var ajaxUrlUpd 	 = '<?= $this->url(array('controller' => 'admin', 'action' => 'updaterecord')); ?>';
</script>