<div class="container">
	<p class="lead pb-3">Inserisci un nuovo dipartimento.</p>

	<?php
		$ok = isset($_GET['ok']) ? $_GET['ok'] : '';
	?>
	<?php if ($ok == 1) : ?>
		<div class="alert alert-success" role="alert">
			<strong>Dipartimento inserito correttamente!</strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<?php endif; ?>

	<form class="need-validation mb-3" action="<?php echo $this->url(array('controller' => 'admin','action' => 'insertdepartment')); ?>" method="POST" novalidate>
		<div class="form-group">
			<label for="InputDepartment">Nome Dipartimento</label>
			<input type="text" class="form-control" name="name" id="InputDepartment" placeholder="Inserisci il nome del dipartimento" required>
		    <div class="invalid-feedback">
		    	Per favore inserisci un nome.
		    </div>
		</div>
		<div class="form-group">
			<label for="InputDescription">Descrizione</label>
			<textarea class="form-control" id="InputDescription" rows="3" name="description" placeholder="Inserisci una descrizione" required></textarea>
		    <div class="invalid-feedback">
		    	Per favore inserisci una descrizione.
		    </div>
		</div>
		<div class="form-group">
			<label for="InputPlace">Luogo</label>
			<input type="text" class="form-control" name="place" id="InputPlace" placeholder="Inserisci il luogo del dipartimento" required>
		    <div class="invalid-feedback">
		    	Per favore inserisci un luogo.
		    </div>
		</div>

		<button type="submit" class="btn btn-primary">Inserisci</button>
	</form>
</div>

<script>
	var validationForm = true;
</script>