<div class="container">
	<p class="lead pb-3">Inserisci una nuova prenotazione.</p>

	<?php
		$ok = isset($_GET['ok']) ? $_GET['ok'] : '';
	?>
	<?php if ($ok == 1) : ?>
		<div class="alert alert-success" role="alert">
			<strong>Prenotazione inserita correttamente!</strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<?php endif; ?>

	<form class="need-validation mb-3" id="bookByAdmin" action="<?php echo $this->url(array('controller' => 'admin','action' => 'insertbooking')); ?>" method="POST" novalidate>
		<div class="form-group">
			<label for="InputUser">Utente</label>
			<select class="form-control" name="user" id="InputUser" required>
				<option value="">Scegli un utente...</option>
				<?php
					foreach ($this->allUser as $value) {
						echo '<option value="'.$value['user_id'].'">'.$value['name'].' '.$value['surname'].'</option>';
					}
				?>
			</select>
		</div>
		<div class="form-group">
			<label for="InputService">Servizio</label>
			<select class="form-control" name="service" id="InputService" required>
				<option value="">Scegli un servizio...</option>
				<?php
					foreach ($this->allService as $value) {
						echo '<option value="'.$value['service_id'].'">'.$value['name'].'</option>';
					}
				?>
			</select>
		</div>
		<div class="form-group">
			<label for="datetimepicker">Scegli la data</label>
			<div class="mx-auto my-0" style="max-width: 550px;" id="datetimepicker"></div>
			<input type="hidden" name="date" id="InputDate">
		</div>

		<button type="submit" class="btn btn-primary">Inserisci</button>
	</form>
</div>

<script>
	var validationForm = true;
	var adminInsertBooking = true;
	var urlAjaxBookingCheck = '<?= $this->url(array('controller' => 'admin', 'action' => 'insertbookingadmin')); ?>';
</script>