<div class="container pb-4">
	<h2 class="mb-3">Gestione Servizi</h2>
	<p class="lead pb-3">In questa pagina è possibile vedere tutte le prestazioni offerte con la possibilitò di modificarli, inserirne nuovi e/o cancellarli.</p>

	<div class="text-center">
		<a href="<?= $this->url(array('controller' => 'admin', 'action' => 'insertservice')); ?>" class="btn btn-outline-success"><i class="fas fa-plus-circle"></i> Inserisci nuovo</a>
	</div>
	
	<div class="table-responsive mt-2">
		<table id="dataTable" class="table table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>Servizio</th>
	                <th>Dipartimento</th>
	                <th>Descrizione</th>
	                <th>Dottore</th>
	                <th>Prescrizioni</th>
	                <th>Orario</th>
	                <th>Azioni</th>
	            </tr>
	        </thead>
	        <tbody>
	        	<?php
	        		foreach ($this->allService as $value) {
	        			$desc = strlen($value['description']) > 100 ? substr($value['description'], 0, 100).'...' : $value['description'];
	        			echo '<tr id="row'.$value['service_id'].'">';
	        			echo '<td>'.$value['name'].'</td>';
	        			echo '<td>'.$value['department'].'</td>';
	        			echo '<td>'.$desc.'</td>';
	        			echo '<td>'.$value['staff_name'].' '.$value['surname'].'</td>';
	        			echo '<td>'.$value['prescriptions'].'</td>';
	        			echo '<td class="text-center text-white"><a class="btn btn-info btn-sm openScheduleModal" data-schedule=\''.$value['schedule'].'\'>Vedi</a></td>';
						echo '<td class="text-center">';
							echo '<a class="text-dark deleteAction" data-toggle="tooltip" data-placement="top" title="Cancella" data-primary="'.$value['service_id'].'"><i class="fas fa-trash-alt"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark updateAction" data-toggle="tooltip" data-placement="top" title="Modifica" data-primary="'.$value['service_id'].'" data-toggle="modal" data-target="#updateModal"><i class="fas fa-edit"></i></a>';
						echo '</td>';
	        			echo '</tr>';
	        		}
	        	?>
	        </tbody>
	    </table>
	</div>
</div>


<!-- Update Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modifica Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<form>
		<div class="form-group">
			<label for="InputService">Nome Servizio</label>
			<input type="text" class="form-control modalInput-name" name="name" id="InputService" placeholder="Inserisci il nome del servizio" required>
		    <div class="invalid-feedback">
		    	Per favore inserisci il nome del servizio.
		    </div>
		</div>
		<div class="form-group">
			<label for="InputDepartment">Dipartimento</label>
			<select class="form-control modalInput-department" name="department"></select>
		</div>
		<div class="form-group">
			<label for="InputDescription">Descrizione</label>
			<textarea class="form-control modalInput-description" id="InputDescription" rows="3" name="description" placeholder="Inserisci una descrizione" required></textarea>
		    <div class="invalid-feedback">
		    	Per favore inserisci la descrizione del servizio.
		    </div>
		</div>
		<div class="form-group">
			<label for="InputDepartment">Dottore</label>
			<select class="form-control modalInput-doctor" name="staff"></select>
		</div>
		<div class="form-group">
			<label for="InputHours">Orari di apertura e chiusura</label><br>

			<div class="row mb-4">
				<div class="col-md-6">
					<!-- ////////////// LUNEDI ////////////// -->
					<h6 class="text-center">Lunedì</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-1">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-1">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-1">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-1">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<!-- ////////////// MARTEDI ////////////// -->
					<h6 class="text-center">Martedì</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-2">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-2">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-2">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-2">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
			</div><!-- /row - LUN MAR -->

			<hr>

			<div class="row mt-3">
				<div class="col-md-6">
					<!-- ////////////// MERCOLEDI ////////////// -->
					<h6 class="text-center">Mercoledì</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-3">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-3">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-3">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-3">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<!-- ////////////// GIOVEDI ////////////// -->
					<h6 class="text-center">Giovedì</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-4">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-4">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-4">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-4">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
			</div><!-- /row - MER GIO -->

			<hr>

			<div class="row mt-3">
				<div class="col-md-6">
					<!-- ////////////// VENERDI ////////////// -->
					<h6 class="text-center">Venerdì</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-5">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-5">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-5">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-5">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<!-- ////////////// SABATO ////////////// -->
					<h6 class="text-center">Sabato</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-6">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-6">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-6">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-6">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
			</div><!-- /row - VEN SAB -->

			<hr>

			<div class="row mt-3">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<!-- ////////////// DOMENICA ////////////// -->
					<h6 class="text-center">Domenica</h6>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;mattina&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="m_opening-0">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="m_closing-0">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
					<small class="d-block text-center position-relative pt-2 matPom"><mark>&nbsp;pomeriggio&nbsp;</mark></small>
					<div class="row">
						<div class="col-sm-6">
							<label class="text-left"><em>Apertura</em></label>
							<select class="form-control" name="a_opening-0">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php
							    	for ($i = 0; $i < 24; $i++) { 
							    		echo '<option value="'.$i.':00">'.$i.':00</option>';
							    	}
							    ?>
							</select>
						</div>
						<div class="col-sm-6">
							<label class="d-block text-right"><em>Chiusura</em></label>
							<select class="form-control" name="a_closing-0">
							    <option value="invariato">Inviariato</option>
							    <option value="">Chiuso</option>
							    <?php for ($i = 0; $i < 24; $i++) { echo '<option value="'.$i.':00">'.$i.':00</option>'; } ?>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-2"></div>
			</div><!-- /row - DOM -->

		</div><!-- /form-group -->
		<div class="form-group">
			<label for="InputPlace">Prescrizione</label>
			<input type="text" class="form-control modalInput-prescriptions" name="prescriptions" id="InputPlace" placeholder="Inserisci eventuali prescrizioni">
		</div>
      		<input type="hidden" name="typeOfRecord" value="service">
      		<input type="hidden" name="primariKey" class="modalInput-key">
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <button type="button" class="btn btn-primary" id="sendUpdateBook">Modifica</button>
      </div>
    </div>
  </div>
</div>

<!-- Hours Modal -->
<div class="modal fade" id="hoursModal" tabindex="-1" role="dialog" aria-labelledby="hoursModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="hoursModalLabel">Orario Servizio</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
			<section class="schedule">
				<div class="table-responsive">
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th scope="col">Giorno</th>
								<th scope="col">Orario Mattina</th>
								<th scope="col">Orario Pomeriggio</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</section>
      </div>
    </div>
  </div>
</div>

<script>
	var dataTableInit = true;

	var typeOfRecord = 'service';
	var ajaxUrlDel   = '<?= $this->url(array('controller' => 'admin', 'action' => 'deleterecord')); ?>';
	var ajaxUrlGet   = '<?= $this->url(array('controller' => 'admin', 'action' => 'getrecord')); ?>';
	var ajaxUrlUpd 	 = '<?= $this->url(array('controller' => 'admin', 'action' => 'updaterecord')); ?>';
</script>