<div class="container">
	<h2 class="mb-3">Gestione Utenti</h2>
	<p class="lead pb-3">In questa pagina è possibile vedere tutti gli utenti registrati al sito con la possibilitò di modificarli e/o cancellarli.</p>
	
	<div class="table-responsive mt-2">
		<table id="dataTable" class="table table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>Username</th>
	                <th>Nome</th>
	                <th>Cognome</th>
	                <th>Codice Fiscale</th>
	                <th>Email</th>
	                <th>Azioni</th>
	            </tr>
	        </thead>
	        <tbody>
	        	<?php
	        		foreach ($this->allUser as $value) {
	        			echo '<tr id="row'.$value['user_id'].'">';
	        			echo '<td>'.$value['username'].'</td>';
	        			echo '<td>'.$value['name'].'</td>';
	        			echo '<td>'.$value['surname'].'</td>';
	        			echo '<td>'.$value['code'].'</td>';
	        			echo '<td>'.$value['email'].'</td>';
						echo '<td class="text-center">';
							echo '<a class="text-dark deleteAction" data-toggle="tooltip" data-placement="top" title="Cancella" data-primary="'.$value['user_id'].'"><i class="fas fa-trash-alt"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark updateAction" data-toggle="tooltip" data-placement="top" title="Modifica" data-primary="'.$value['user_id'].'" data-toggle="modal" data-target="#updateModal"><i class="fas fa-edit"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark" data-toggle="tooltip" data-placement="top" title="Statistiche" href="'.$this->url(array('controller' => 'admin', 'action' => 'userstats', 'id' => $value['user_id'])).'"><i class="fas fa-chart-pie"></i></a>';
						echo '</td>';
	        			echo '</tr>';
	        		}
	        	?>
	        </tbody>
	    </table>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modifica Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
		<form>
			<div class="form-group">
				<label>Username</label>
      			<input type="text" name="username" class="form-control modalInput-username">
			</div>
			<div class="form-group">
				<label>Nome</label>
      			<input type="text" name="name" class="form-control modalInput-name">
			</div>
			<div class="form-group">
				<label>Cognome</label>
      			<input type="text" name="surname" class="form-control modalInput-surname">
			</div>
			<div class="form-group">
				<label>Codice Fiscale</label>
      			<input type="text" name="code" class="form-control modalInput-code">
			</div>
			<div class="form-group">
				<label>Email</label>
      			<input type="text" name="email" class="form-control modalInput-email">
			</div>
      		<input type="hidden" name="typeOfRecord" value="user">
      		<input type="hidden" name="primariKey" class="modalInput-key">
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <button type="button" class="btn btn-primary" id="sendUpdateBook">Modifica</button>
      </div>
    </div>
  </div>
</div>

<script>
	var dataTableInit = true;

	var typeOfRecord = 'user';
	var ajaxUrlDel   = '<?= $this->url(array('controller' => 'admin', 'action' => 'deleterecord')); ?>';
	var ajaxUrlGet   = '<?= $this->url(array('controller' => 'admin', 'action' => 'getrecord')); ?>';
	var ajaxUrlUpd 	 = '<?= $this->url(array('controller' => 'admin', 'action' => 'updaterecord')); ?>';
</script>