<div class="container">
	<h2 class="mb-3">Gestione Utenti</h2>
	<p class="lead pb-3">In questa pagina è possibile vedere tutti gli utenti registrati al sito con la possibilitò di modificarli e/o cancellarli.</p>
	
	<div class="table-responsive mt-2">
		<table id="dataTable" class="table table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>Username</th>
	                <th>Nome</th>
	                <th>Cognome</th>
	                <th>Codice Fiscale</th>
	                <th>Email</th>
	                <th>Azioni</th>
	            </tr>
	        </thead>
	        <tbody>
	        	<?php
	        		foreach ($this->allUser as $value) {
	        			echo '<tr>';
	        			echo '<td>'.$value['username'].'</td>';
	        			echo '<td>'.$value['name'].'</td>';
	        			echo '<td>'.$value['surname'].'</td>';
	        			echo '<td>'.$value['code'].'</td>';
	        			echo '<td>'.$value['email'].'</td>';
						echo '<td class="text-center">';
							echo '<a class="text-dark deleteAction" data-toggle="tooltip" data-placement="top" title="Cancella" data-booking="'.$value['user_id'].'"><i class="fas fa-trash-alt"></i></a>';
							echo '&nbsp;&nbsp;&nbsp;';
							echo '<a class="text-dark updateAction" data-toggle="tooltip" data-placement="top" title="Modifica" data-booking="'.$value['user_id'].'" data-toggle="modal" data-target="#updateModal"><i class="fas fa-edit"></i></a>';
						echo '</td>';
	        			echo '</tr>';
	        		}
	        	?>
	        </tbody>
	    </table>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modifica Record</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <button type="button" class="btn btn-primary" id="sendUpdateBook">Modifica</button>
      </div>
    </div>
  </div>
</div>

<script>
	var dataTableInit = true;
</script>